version: '3'
services:
  controller:
    image: lscr.io/linuxserver/unifi-controller
    restart: unless-stopped
    expose:
      - 8443 #Web admin port
      - 3478/udp #STUN port
      - 10001/udp #Required for AP discovery
      - 8080 #Required for device communcation
      #- 1900/udp #Required for "Make controller discoverable on L2 network" option
      #- 8843 #Guest portal HTTPS redirect port
      #- 8880 #Guest portal HTTP redirect port
      #- 6789 #For mobile throughput test
      - 5514/udp #Remote syslog port
    environment:
      PUID: ${PUID:?Missing PUID}
      PGID: ${PGID:?Missing PGID}
      TZ: ${TZ:-UTC}
      VIRTUAL_HOST: ${VIRTUAL_HOST:?Missing VIRTUAL_HOST}
      LETSENCRYPT_HOST: ${VIRTUAL_HOST:?Missing VIRTUAL_HOST}
      LETSENCRYPT_EMAIL: ${LETSENCRYPT_EMAIL}
      DEBUG: ${DEBUG:-false}
    volumes:
      - ./:/config
    networks:
      - network
      - nginx-proxy
networks:
  network:
  nginx-proxy:
    name: nginx-proxy
    external: true